spring:
  application:
    name: spring-ai-demo
  ai:
    model:
      # These values must be one of the listed LLMs below
      chat: anthropic
      # Spring AI doesn't support an Anthropic embedding model.
      # Use OpenAI or Ollama's embedding model. Need to rebuild the vector store when switching
      embedding: openai
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-3-small
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        options:
          model: claude-3-7-sonnet-latest
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
      embedding:
        options:
          enabled: true
          model: nomic-embed-text
    mcp:
      client:
        enabled: true
        name: brave-search
        version: 1.0.0
        request-timeout: 20s
        type: SYNC  # or ASYNC for reactive applications
        toolcallback.enabled: true
        stdio:
          root-change-notification: true
          connections:
            brave-search:
              command: npx.cmd
              args: -y,@modelcontextprotocol/server-brave-search
#              args:
#                - "-y"
#                - "@modelcontextprotocol/server-brave-search"
              env:
                BRAVE_API_KEY: ${BRAVE_API_KEY}

ai-app:
  vectorStorePath: /temp/vectorStore.json
  # the trimmed csv file removed a lot of extra fields to refine the search criteria
  documentsToLoad:
    - classpath:/movies500.csv
  api-ninjas-key: ${API_NINJAS_KEY}
