spring:
  application:
    name: basic-chatbot
  main:
    banner-mode: off
  ai:
    model:
      # These values must be one of the listed LLMs below
      chat: anthropic
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        options:
          model: claude-3-7-sonnet-latest
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
