spring:
  application:
    name: basic-chatbot
  main:
    banner-mode: off
  ai:
    model:
      # These values must be one of the listed LLMs below
      chat: anthropic
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        options:
          model: claude-3-7-sonnet-latest
    mcp:
      client:
        enabled: true
        name: brave-search
        version: 1.0.0
        request-timeout: 20s
        type: SYNC  # or ASYNC for reactive applications
        toolcallback.enabled: true
        stdio:
          root-change-notification: true
          connections:
            brave-search:
              command: npx.cmd
              args: -y,@modelcontextprotocol/server-brave-search
              env:
                BRAVE_API_KEY: ${BRAVE_API_KEY}
        sse:
          connections:
            weather-mcp-service:
              url: http://localhost:8081
